# Rebuild maintainsmip-guru from SYSTEM_PROMPT.md + parameters.
# Usage: cd C:\MaintainSMIP ; .\ollama\build.ps1

$ErrorActionPreference = 'Stop'
$Root = Split-Path $PSScriptRoot -Parent
$PromptFile = Join-Path $PSScriptRoot 'SYSTEM_PROMPT.md'
$Modelfile = Join-Path $PSScriptRoot 'Modelfile'
$ModelName = 'maintainsmip-guru'

$BaseModel = 'maxwell1500/ornith-35b:IQ3_M'

$Parameters = @(
    'PARAMETER temperature 0.2',
    'PARAMETER top_p 0.9',
    'PARAMETER top_k 20',
    'PARAMETER repeat_penalty 1',
    'PARAMETER num_ctx 32768'
)

if (-not (Test-Path $PromptFile)) {
    Write-Error "Missing $PromptFile"
}

$raw = Get-Content $PromptFile -Raw
$parts = $raw -split '(?m)^---\s*$', 2
if ($parts.Count -lt 2) {
    Write-Error "SYSTEM_PROMPT.md must contain a '---' line before the prompt body"
}
$prompt = $parts[1].Trim()

$lines = @(
    "# Auto-generated by ollama/build.ps1 - edit SYSTEM_PROMPT.md then rebuild",
    "FROM $BaseModel",
    ''
) + $Parameters + @(
    '',
    'SYSTEM """',
    $prompt,
    '"""'
)

Set-Content -Path $Modelfile -Value ($lines -join "`n") -Encoding UTF8
Write-Host "Wrote $Modelfile"

Push-Location $Root
try {
    ollama create $ModelName -f $Modelfile
    if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
    Write-Host "Model $ModelName rebuilt successfully."
    ollama show $ModelName | Select-Object -First 12
}
finally {
    Pop-Location
}